CREATE TABLE IF NOT EXISTS articles (
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	title STRING NOT NULL,
	slug STRING NOT NULL UNIQUE,
	content STRING NOT NULL,
	pub_date STRING NOT NULL,
	upd_date STRING NOT NULL,
	published BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	title STRING NOT NULL UNIQUE
);


CREATE TABLE IF NOT EXISTS articles_tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
	article INTEGER,
	tag INTEGER
);
