#! /bin/bash

# originaly from http://tinyurl.com/twitch-linux from taladan
# www.youtube.com/user/taladan

# gist created by brodul

# set mc winsize
xdotool windowsize $(xwininfo -name "Minecraft 1.6.4" | awk '/xwininfo/ {print $4}') 1280 750

INRES=`xwininfo -name "Minecraft 1.6.4" | awk '/geometry/ {print $2}' | sed -e 's/\+.*//g'`
#INRES="1280x800" # input resolution
#OUTRES="1280x720" # Output resolution
OUTRES="640x380" # Output resolution
#OUTRES="$INRES" # Output resolution
FPS="18" # target FPS
QUAL="fast" # one of the many FFMPEG preset on (k)ubuntu found in /usr/share/ffmpeg
# If you have low bandwidth, put the qual preset on 'fast' (upload bandwidth)
# If you have medium bandwitch put it on normal to medium


CORNER=`xwininfo -name "Minecraft 1.6.4" | awk '/Corners/ {print $2}' | sed -re 's/\+(.*)\+(.*)/+\1,\2/'`

echo "INRES: $INRES CORNER: $CORNER"

# Write your key in a file named .twitch_key in your home directory
STREAM_KEY=$(cat ~/.twitch_key) # This is your streamkey generated by jtv/twitch found at: http://www.justin.tv/broadcast/adv_other

URL="rtmp://live-ams.twitch.tv/app/"
#BITRATE=2048000
BITRATE=1024000

/home/stasikos/tmp/ffmpeg/ffmpeg/ffmpeg \
-f x11grab -s $INRES -framerate "$FPS" -i :0.0"$CORNER" \
-f alsa -i pulse -ac 2  \
-vcodec libx264 -s $OUTRES -preset $QUAL \
-g 32 -keyint_min 18 -pix_fmt yuv420p -tune film -async 1 \
-acodec libmp3lame -ar 44100 -threads 0 -b $BITRATE -bufsize 1000k \
-f flv "${URL}${STREAM_KEY}"